### ISSUE TITLE
[建议][01]: 斯卡蒂一开始应该用泳装皮肤素材

### ISSUE THREAD

**Issue by 1436735995** [FDT-Studio/FDTGameProject#19]
### 背景与动机

其实我一直都想说，为什么CG事泳装皮肤的斯卡蒂，而前面对话那里要用原皮，如果非要用站着的立绘，为什么不开动AI再增补一张CG呢？（我知道这个项目已经不再更新了，但是希望正式版的时候能好好考虑一下下，而且不要像这回一样不动声色，其实在开发中提建议是最好的）

### 想要实现或优化的功能

将斯卡蒂原皮替换成泳装皮肤立绘或者增补立绘

**Comment by Misaka2298** [comment]
斯卡蒂有泳装立绘吗（）我跟秦川找了好久都没找到
