### ISSUE TITLE
[建议][01]: 标题图片英文写错了

### ISSUE THREAD

**Issue by 1436735995** [FDT-Studio/FDTGameProject#20]
### 背景与动机

斯卡蒂的英文是Skadi，而项目里的大标题的英文写成了SKATI
https://github.com/FDT-Studio/FDTGameProject/tree/SkadiDemo01
不过现在已经无所谓了，下次再注意吧

### 想要实现或优化的功能

斯卡蒂的英文是Skadi，而项目里的大标题的英文写成了SKATI
https://github.com/FDT-Studio/FDTGameProject/tree/SkadiDemo01
PS改过来就行了

**Comment by Misaka2298** [comment]
草，感谢

**Comment by Misaka2298** [comment]
草，PS没保存工程文件，算了算了，正式版会注意的（）
